export interface ArtStyle {
  id: string;
  name: string;
  description: string;
  prompt: string;
  emoji: string;
  category: 'historical' | 'modern' | 'digital' | 'photography' | 'illustration';
}

export const artStyles: ArtStyle[] = [
  // Historical Art Movements
  {
    id: 'renaissance',
    name: 'Renaissance',
    description: 'Classical Italian art with realistic proportions',
    prompt: 'in Renaissance art style, classical composition, realistic proportions, chiaroscuro lighting, oil painting technique, sfumato',
    emoji: '🎨',
    category: 'historical',
  },
  {
    id: 'baroque',
    name: 'Baroque',
    description: 'Dramatic lighting and ornate details',
    prompt: 'in Baroque style, dramatic lighting, rich details, dynamic composition, ornate elements, Caravaggio-inspired, tenebrism',
    emoji: '👑',
    category: 'historical',
  },
  {
    id: 'impressionism',
    name: 'Impressionism',
    description: 'Soft brushstrokes capturing light and movement',
    prompt: 'in Impressionist style, visible brushstrokes, emphasis on light and color, loose composition, plein air aesthetic, Monet-inspired',
    emoji: '🌅',
    category: 'historical',
  },
  {
    id: 'post-impressionism',
    name: 'Post-Impressionism',
    description: 'Vivid colors and bold forms',
    prompt: 'in Post-Impressionist style, vivid colors, bold forms, expressive brushwork, Van Gogh-inspired, emotional intensity',
    emoji: '🌻',
    category: 'historical',
  },
  {
    id: 'art-nouveau',
    name: 'Art Nouveau',
    description: 'Flowing organic lines and decorative elements',
    prompt: 'in Art Nouveau style, flowing organic lines, ornate details, nature-inspired motifs, Alphonse Mucha aesthetic, elegant curves',
    emoji: '🌿',
    category: 'historical',
  },
  {
    id: 'art-deco',
    name: 'Art Deco',
    description: 'Bold geometric patterns and luxury',
    prompt: 'in Art Deco style, geometric patterns, symmetrical design, metallic accents, 1920s glamour, streamline moderne',
    emoji: '✨',
    category: 'historical',
  },
  {
    id: 'cubism',
    name: 'Cubism',
    description: 'Geometric shapes and multiple perspectives',
    prompt: 'in Cubist style, geometric fragmentation, multiple perspectives, abstract forms, Picasso-inspired, analytical cubism',
    emoji: '📐',
    category: 'historical',
  },
  {
    id: 'surrealism',
    name: 'Surrealism',
    description: 'Dreamlike and fantastical imagery',
    prompt: 'in Surrealist style, dreamlike imagery, unexpected juxtapositions, symbolic elements, Salvador Dalí-inspired, subconscious exploration',
    emoji: '🌙',
    category: 'historical',
  },
  {
    id: 'expressionism',
    name: 'Expressionism',
    description: 'Intense colors and emotional distortion',
    prompt: 'in Expressionist style, bold colors, emotional intensity, distorted forms, dramatic contrast, Munch-inspired',
    emoji: '🎭',
    category: 'historical',
  },
  {
    id: 'ukiyo-e',
    name: 'Ukiyo-e',
    description: 'Japanese woodblock prints',
    prompt: 'in Ukiyo-e style, Japanese woodblock print, flat colors, bold outlines, Hokusai-inspired, traditional Japanese art',
    emoji: '🗾',
    category: 'historical',
  },

  // Modern Art Styles
  {
    id: 'minimalism',
    name: 'Minimalism',
    description: 'Clean lines and simple compositions',
    prompt: 'in Minimalist style, clean lines, simple forms, negative space, limited color palette, contemporary aesthetic, essential elements',
    emoji: '⬜',
    category: 'modern',
  },
  {
    id: 'pop-art',
    name: 'Pop Art',
    description: 'Bold colors and commercial imagery',
    prompt: 'in Pop Art style, bold colors, commercial imagery, Ben-Day dots, Andy Warhol aesthetic, graphic design elements, screen printing effect',
    emoji: '🎪',
    category: 'modern',
  },
  {
    id: 'abstract',
    name: 'Abstract',
    description: 'Non-representational forms and colors',
    prompt: 'in Abstract style, non-representational forms, bold colors, gestural marks, emphasis on composition and color theory, Kandinsky-inspired',
    emoji: '🌈',
    category: 'modern',
  },
  {
    id: 'street-art',
    name: 'Street Art',
    description: 'Urban graffiti and stencil techniques',
    prompt: 'in Street Art style, urban aesthetic, graffiti elements, bold graphics, Banksy-inspired, stencil techniques, spray paint texture',
    emoji: '🏙️',
    category: 'modern',
  },
  {
    id: 'watercolor',
    name: 'Watercolor',
    description: 'Soft washes and flowing colors',
    prompt: 'in Watercolor style, soft color washes, flowing pigments, paper texture, translucent layers, organic blending, wet-on-wet technique',
    emoji: '💧',
    category: 'modern',
  },
  {
    id: 'collage',
    name: 'Collage',
    description: 'Mixed media and layered elements',
    prompt: 'in Collage style, mixed media, layered elements, cut paper aesthetic, photomontage, varied textures',
    emoji: '✂️',
    category: 'modern',
  },
  {
    id: 'grunge',
    name: 'Grunge',
    description: 'Distressed textures and raw aesthetic',
    prompt: 'in Grunge style, distressed textures, raw aesthetic, torn edges, weathered look, gritty urban feel',
    emoji: '🎸',
    category: 'modern',
  },

  // Digital & Contemporary
  {
    id: 'synthwave',
    name: 'Synthwave',
    description: 'Retro futuristic 80s aesthetic',
    prompt: 'in Synthwave style, neon colors, retro futuristic, 80s aesthetic, grid patterns, sunset gradients, Miami Vice vibes',
    emoji: '🌆',
    category: 'digital',
  },
  {
    id: 'cyberpunk',
    name: 'Cyberpunk',
    description: 'High-tech dystopian future',
    prompt: 'in Cyberpunk style, neon lights, futuristic cityscape, high-tech low-life, dystopian atmosphere, digital elements, Blade Runner aesthetic',
    emoji: '🤖',
    category: 'digital',
  },
  {
    id: 'vaporwave',
    name: 'Vaporwave',
    description: 'Nostalgic internet aesthetic',
    prompt: 'in Vaporwave style, pastel colors, retro computer graphics, 90s internet aesthetic, glitch effects, Roman busts, palm trees',
    emoji: '💜',
    category: 'digital',
  },
  {
    id: 'anime',
    name: 'Anime',
    description: 'Japanese animation style',
    prompt: 'in Anime style, cel-shaded, expressive eyes, vibrant colors, Japanese animation aesthetic, detailed backgrounds, Studio Ghibli inspired',
    emoji: '🎌',
    category: 'digital',
  },
  {
    id: 'pixel-art',
    name: 'Pixel Art',
    description: 'Retro video game graphics',
    prompt: 'in Pixel Art style, 8-bit graphics, limited color palette, retro gaming aesthetic, pixelated details, dithering',
    emoji: '🎮',
    category: 'digital',
  },
  {
    id: 'low-poly',
    name: 'Low Poly',
    description: 'Geometric 3D shapes',
    prompt: 'in Low Poly style, geometric 3D shapes, flat shading, polygonal aesthetic, clean edges, modern digital art, faceted surfaces',
    emoji: '🔷',
    category: 'digital',
  },
  {
    id: 'glitch-art',
    name: 'Glitch Art',
    description: 'Digital corruption aesthetic',
    prompt: 'in Glitch Art style, digital corruption, data moshing, RGB shift, pixel sorting, technological errors, cybernetic aesthetic',
    emoji: '📺',
    category: 'digital',
  },
  {
    id: 'isometric',
    name: 'Isometric',
    description: '3D geometric perspective',
    prompt: 'in Isometric style, 30-degree angles, 3D perspective, geometric precision, technical illustration, video game aesthetic',
    emoji: '🎲',
    category: 'digital',
  },
  {
    id: 'neon',
    name: 'Neon',
    description: 'Glowing neon light aesthetic',
    prompt: 'in Neon style, glowing lights, bright neon colors, dark background, electric glow, sign aesthetic, luminous outlines',
    emoji: '💡',
    category: 'digital',
  },
  {
    id: 'holographic',
    name: 'Holographic',
    description: 'Iridescent rainbow effects',
    prompt: 'in Holographic style, iridescent colors, rainbow gradient, metallic sheen, futuristic aesthetic, chromatic aberration',
    emoji: '🌈',
    category: 'digital',
  },

  // Photography Styles
  {
    id: 'cinematic',
    name: 'Cinematic',
    description: 'Film-like color grading and composition',
    prompt: 'cinematic photography, film grain, color grading, wide aspect ratio, dramatic lighting, movie still aesthetic, depth of field',
    emoji: '🎬',
    category: 'photography',
  },
  {
    id: 'vintage-photo',
    name: 'Vintage Photography',
    description: 'Old film camera aesthetic',
    prompt: 'vintage photography, faded colors, film grain, retro aesthetic, nostalgic feel, aged photo look, 70s photography',
    emoji: '📷',
    category: 'photography',
  },
  {
    id: 'black-white',
    name: 'Black & White',
    description: 'Monochrome photography',
    prompt: 'black and white photography, high contrast, grayscale, dramatic shadows, monochrome, fine art photography, Ansel Adams inspired',
    emoji: '⚫',
    category: 'photography',
  },
  {
    id: 'golden-hour',
    name: 'Golden Hour',
    description: 'Warm sunset lighting',
    prompt: 'golden hour photography, warm sunlight, soft glow, magic hour, sunset lighting, amber tones, natural beauty',
    emoji: '🌇',
    category: 'photography',
  },
  {
    id: 'macro',
    name: 'Macro',
    description: 'Extreme close-up details',
    prompt: 'macro photography, extreme close-up, fine details, shallow depth of field, textural details, micro world',
    emoji: '🔬',
    category: 'photography',
  },
  {
    id: 'long-exposure',
    name: 'Long Exposure',
    description: 'Motion blur and light trails',
    prompt: 'long exposure photography, motion blur, light trails, smooth water, star trails, ethereal movement',
    emoji: '⭐',
    category: 'photography',
  },
  {
    id: 'portrait',
    name: 'Portrait',
    description: 'Professional portraiture',
    prompt: 'portrait photography, professional lighting, bokeh background, sharp focus on subject, studio quality, flattering angles',
    emoji: '👤',
    category: 'photography',
  },
  {
    id: 'landscape',
    name: 'Landscape',
    description: 'Sweeping natural vistas',
    prompt: 'landscape photography, wide angle, sweeping vista, natural beauty, dramatic sky, foreground interest, depth',
    emoji: '🏔️',
    category: 'photography',
  },
  {
    id: 'hdr',
    name: 'HDR',
    description: 'High dynamic range imagery',
    prompt: 'HDR photography, high dynamic range, detailed shadows and highlights, vibrant colors, hyper-realistic, tone-mapped',
    emoji: '🌟',
    category: 'photography',
  },
  {
    id: 'tilt-shift',
    name: 'Tilt-Shift',
    description: 'Miniature effect photography',
    prompt: 'tilt-shift photography, miniature effect, selective focus, toy-like appearance, shallow depth of field band',
    emoji: '🏘️',
    category: 'photography',
  },

  // Illustration Styles
  {
    id: 'cartoon',
    name: 'Cartoon',
    description: 'Classic cartoon illustration',
    prompt: 'cartoon illustration style, bold outlines, flat colors, exaggerated features, playful aesthetic, animated look',
    emoji: '🎨',
    category: 'illustration',
  },
  {
    id: 'comic-book',
    name: 'Comic Book',
    description: 'Superhero comic style',
    prompt: 'comic book art style, bold inking, halftone dots, dynamic poses, action lines, Marvel/DC aesthetic, panel composition',
    emoji: '💥',
    category: 'illustration',
  },
  {
    id: 'manga',
    name: 'Manga',
    description: 'Japanese comic style',
    prompt: 'manga art style, black and white, screentones, speed lines, expressive emotions, Japanese comic aesthetic',
    emoji: '📖',
    category: 'illustration',
  },
  {
    id: 'line-art',
    name: 'Line Art',
    description: 'Clean linework illustration',
    prompt: 'line art style, clean lines, no shading, outline drawing, vector-like, minimalist illustration, contour drawing',
    emoji: '✏️',
    category: 'illustration',
  },
  {
    id: 'sketch',
    name: 'Sketch',
    description: 'Hand-drawn pencil aesthetic',
    prompt: 'sketch style, pencil drawing, rough lines, hand-drawn look, gestural marks, artistic process, loose illustration',
    emoji: '✍️',
    category: 'illustration',
  },
  {
    id: 'ink',
    name: 'Ink Drawing',
    description: 'Traditional ink illustration',
    prompt: 'ink drawing style, pen and ink, crosshatching, stippling, traditional illustration, bold black lines',
    emoji: '🖋️',
    category: 'illustration',
  },
  {
    id: 'childrens-book',
    name: "Children's Book",
    description: 'Whimsical storybook illustration',
    prompt: "children's book illustration, whimsical, soft colors, friendly characters, storybook aesthetic, charming details",
    emoji: '📚',
    category: 'illustration',
  },
  {
    id: 'flat-design',
    name: 'Flat Design',
    description: 'Modern flat illustration',
    prompt: 'flat design illustration, simple shapes, solid colors, no gradients, geometric forms, modern vector style',
    emoji: '🎯',
    category: 'illustration',
  },
  {
    id: 'retro-poster',
    name: 'Retro Poster',
    description: 'Vintage poster design',
    prompt: 'retro poster style, vintage typography, limited color palette, propaganda poster aesthetic, bold graphics, screen print look',
    emoji: '📜',
    category: 'illustration',
  },
  {
    id: 'psychedelic',
    name: 'Psychedelic',
    description: 'Trippy 60s-70s aesthetic',
    prompt: 'psychedelic art style, swirling patterns, vibrant colors, optical illusions, 60s poster aesthetic, kaleidoscopic',
    emoji: '🌀',
    category: 'illustration',
  },
  {
    id: 'steampunk',
    name: 'Steampunk',
    description: 'Victorian era meets industrial',
    prompt: 'steampunk style, Victorian era, brass and copper, gears and cogs, industrial revolution aesthetic, retro-futuristic',
    emoji: '⚙️',
    category: 'illustration',
  },
  {
    id: 'gothic',
    name: 'Gothic',
    description: 'Dark romantic aesthetic',
    prompt: 'gothic art style, dark romantic, ornate details, medieval influences, dramatic shadows, Tim Burton inspired',
    emoji: '🦇',
    category: 'illustration',
  },
  {
    id: 'kawaii',
    name: 'Kawaii',
    description: 'Cute Japanese aesthetic',
    prompt: 'kawaii style, cute characters, pastel colors, chibi proportions, adorable details, Japanese cute aesthetic',
    emoji: '🎀',
    category: 'illustration',
  },
  {
    id: 'sticker',
    name: 'Sticker',
    description: 'Die-cut sticker design',
    prompt: 'sticker art style, bold outlines, white border, vibrant colors, die-cut appearance, contour line',
    emoji: '🏷️',
    category: 'illustration',
  },
  {
    id: 'vector',
    name: 'Vector Art',
    description: 'Clean scalable graphics',
    prompt: 'vector art style, clean lines, geometric shapes, solid colors, scalable graphics, Adobe Illustrator aesthetic, crisp edges',
    emoji: '🎨',
    category: 'illustration',
  },
  {
    id: 'charcoal',
    name: 'Charcoal Drawing',
    description: 'Dramatic charcoal sketching',
    prompt: 'charcoal drawing style, dramatic shading, smudged textures, tonal values, expressive marks, classical drawing technique',
    emoji: '⚫',
    category: 'illustration',
  },
  {
    id: 'pastel',
    name: 'Pastel',
    description: 'Soft chalk pastel art',
    prompt: 'pastel art style, soft colors, chalk texture, blended edges, delicate tones, traditional pastel technique',
    emoji: '🌸',
    category: 'modern',
  },
  {
    id: 'oil-painting',
    name: 'Oil Painting',
    description: 'Traditional oil painting',
    prompt: 'oil painting style, rich textures, layered paint, visible brushstrokes, classical painting technique, impasto',
    emoji: '🖌️',
    category: 'modern',
  },
  {
    id: 'acrylic',
    name: 'Acrylic',
    description: 'Modern acrylic painting',
    prompt: 'acrylic painting style, vibrant colors, smooth finish, contemporary technique, bold application',
    emoji: '🎨',
    category: 'modern',
  },
  {
    id: 'spray-paint',
    name: 'Spray Paint',
    description: 'Urban spray paint art',
    prompt: 'spray paint art style, aerosol texture, stencil effects, urban aesthetic, graffiti technique, vibrant colors, drips and overspray',
    emoji: '💨',
    category: 'modern',
  },
  {
    id: 'realistic',
    name: 'Photorealistic',
    description: 'Hyper-realistic detail',
    prompt: 'photorealistic style, extreme detail, lifelike rendering, precise accuracy, hyperrealism, trompe-l\'oeil',
    emoji: '👁️',
    category: 'modern',
  },
  {
    id: 'double-exposure',
    name: 'Double Exposure',
    description: 'Layered multiple exposures',
    prompt: 'double exposure photography, layered images, blended scenes, ethereal overlap, transparent overlay, artistic composition',
    emoji: '👥',
    category: 'photography',
  },
  {
    id: 'bokeh',
    name: 'Bokeh',
    description: 'Beautiful background blur',
    prompt: 'bokeh photography, shallow depth of field, creamy background blur, circular light orbs, soft focus, dreamy aesthetic',
    emoji: '✨',
    category: 'photography',
  },
  {
    id: 'silhouette',
    name: 'Silhouette',
    description: 'Dramatic silhouette photography',
    prompt: 'silhouette photography, backlit subjects, dramatic contrast, outline emphasis, sunset silhouettes, minimal detail',
    emoji: '🌅',
    category: 'photography',
  },
  {
    id: 'motion-blur',
    name: 'Motion Blur',
    description: 'Dynamic movement capture',
    prompt: 'motion blur photography, dynamic movement, panning technique, speed effect, kinetic energy, directional blur',
    emoji: '💨',
    category: 'photography',
  },
  {
    id: 'drone',
    name: 'Drone/Aerial',
    description: 'Bird\'s eye view photography',
    prompt: 'drone photography, aerial perspective, bird\'s eye view, top-down composition, landscape from above, unique vantage point',
    emoji: '🚁',
    category: 'photography',
  },
  {
    id: '3d-render',
    name: '3D Render',
    description: 'Computer-generated 3D',
    prompt: '3D render, CGI, ray tracing, photorealistic materials, digital lighting, Blender/Cinema 4D aesthetic, clean renders',
    emoji: '🎲',
    category: 'digital',
  },
  {
    id: 'clay-render',
    name: 'Clay Render',
    description: '3D clay material aesthetic',
    prompt: 'clay render style, matte material, soft lighting, monochrome or pastel, 3D sculpted look, tactile surface',
    emoji: '🏺',
    category: 'digital',
  },
  {
    id: 'wireframe',
    name: 'Wireframe',
    description: '3D wireframe technical',
    prompt: 'wireframe style, technical drawing, grid lines, blueprint aesthetic, geometric structure, transparent surfaces, architectural visualization',
    emoji: '📐',
    category: 'digital',
  },
  {
    id: 'ascii-art',
    name: 'ASCII Art',
    description: 'Text-based imagery',
    prompt: 'ASCII art style, text characters, monospace font, retro computer aesthetic, terminal art, character-based graphics',
    emoji: '💻',
    category: 'digital',
  },
  {
    id: 'datamosh',
    name: 'Datamoshing',
    description: 'Video compression artifacts',
    prompt: 'datamoshing style, compression artifacts, digital decay, motion vectors, glitchy movement, video corruption aesthetic',
    emoji: '📹',
    category: 'digital',
  },
  {
    id: 'y2k',
    name: 'Y2K Aesthetic',
    description: 'Late 90s/early 2000s digital',
    prompt: 'Y2K aesthetic, chrome effects, glossy surfaces, lens flares, metallic textures, early 2000s digital style, futuristic optimism',
    emoji: '💿',
    category: 'digital',
  },
  {
    id: 'abstract-expressionism',
    name: 'Abstract Expressionism',
    description: 'Spontaneous gestural painting',
    prompt: 'Abstract Expressionist style, gestural brushwork, action painting, emotional intensity, Pollock-inspired, spontaneous creation, drips and splatters',
    emoji: '🎨',
    category: 'historical',
  },
  {
    id: 'fauvism',
    name: 'Fauvism',
    description: 'Wild colors and bold forms',
    prompt: 'Fauvist style, wild colors, non-naturalistic palette, bold brushwork, Matisse-inspired, vibrant hues, simplified forms',
    emoji: '🦁',
    category: 'historical',
  },
  {
    id: 'pointillism',
    name: 'Pointillism',
    description: 'Dots of color technique',
    prompt: 'Pointillist style, dots of color, optical mixing, Seurat technique, stippled effect, divisionism, meticulous detail',
    emoji: '🔴',
    category: 'historical',
  },
  {
    id: 'constructivism',
    name: 'Constructivism',
    description: 'Soviet geometric design',
    prompt: 'Constructivist style, geometric abstraction, bold typography, limited color palette, propaganda poster aesthetic, Russian avant-garde',
    emoji: '🏗️',
    category: 'historical',
  },
  {
    id: 'bauhaus',
    name: 'Bauhaus',
    description: 'Functional geometric design',
    prompt: 'Bauhaus style, geometric simplicity, functional design, primary colors, grid-based composition, modernist aesthetic',
    emoji: '⚙️',
    category: 'historical',
  },
  {
    id: 'de-stijl',
    name: 'De Stijl',
    description: 'Mondrian geometric abstraction',
    prompt: 'De Stijl style, geometric abstraction, primary colors, black lines, grid composition, Mondrian-inspired, neoplasticism',
    emoji: '🟥',
    category: 'historical',
  },
  {
    id: 'memphis',
    name: 'Memphis Design',
    description: '80s postmodern design',
    prompt: 'Memphis design style, bold geometric shapes, bright colors, postmodern aesthetic, 80s design, playful patterns, squiggles and grids',
    emoji: '🎨',
    category: 'modern',
  },
  {
    id: 'maximalism',
    name: 'Maximalism',
    description: 'More is more aesthetic',
    prompt: 'maximalist style, abundant details, rich patterns, layered textures, vibrant colors, ornate decoration, visual abundance',
    emoji: '🌺',
    category: 'modern',
  },
  {
    id: 'brutalism',
    name: 'Brutalism',
    description: 'Raw concrete aesthetic',
    prompt: 'brutalist style, raw concrete, geometric blocks, stark composition, institutional aesthetic, rough textures, monumental forms',
    emoji: '🏢',
    category: 'modern',
  },
  {
    id: 'organic',
    name: 'Organic/Biomorphic',
    description: 'Natural flowing forms',
    prompt: 'organic biomorphic style, flowing natural forms, curved shapes, nature-inspired, smooth transitions, cellular structures',
    emoji: '🌿',
    category: 'modern',
  },
  {
    id: 'noir',
    name: 'Film Noir',
    description: 'Dark dramatic shadows',
    prompt: 'film noir style, dramatic shadows, high contrast, venetian blind lighting, 1940s aesthetic, mystery and danger, chiaroscuro',
    emoji: '🎬',
    category: 'photography',
  },
  {
    id: 'sepia',
    name: 'Sepia Tone',
    description: 'Vintage brown tones',
    prompt: 'sepia tone photography, warm brown tones, vintage aesthetic, aged photograph, nostalgic feel, antique photo look',
    emoji: '📜',
    category: 'photography',
  },
  {
    id: 'infrared',
    name: 'Infrared',
    description: 'False color infrared',
    prompt: 'infrared photography, false color, white foliage, surreal landscape, ethereal glow, unusual color spectrum',
    emoji: '🌳',
    category: 'photography',
  },
  {
    id: 'lomography',
    name: 'Lomography',
    description: 'Vintage toy camera aesthetic',
    prompt: 'lomography style, toy camera aesthetic, vignetting, color shifts, light leaks, vintage film look, experimental photography',
    emoji: '📷',
    category: 'photography',
  },
];

export const getStylesByCategory = (category: ArtStyle['category']) => {
  return artStyles.filter(style => style.category === category);
};
